on:
  pull_request:
  push:

name: backwards compatibility
jobs:
    roave_bc_check:
        name: Roave BC Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: set ownership
              run: |
                  # this is to fix GIT not liking owner of the checkout dir
                  chown -R $(id -u):$(id -g) $PWD
            - name: fetch tags
              run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            - name: Roave BC Check
              uses: docker://nyholm/roave-bc-check-ga
