on:
  pull_request:
  push:

name: backwards compatibility

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@add-bc-workflow
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
